/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TrackRouteImport } from './routes/track'
import { Route as StoreRouteImport } from './routes/store'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as PoliciesReplacementRouteImport } from './routes/policies.replacement'
import { Route as PoliciesRefundRouteImport } from './routes/policies.refund'
import { Route as OrdersOrderNumberRouteImport } from './routes/orders.$orderNumber'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNewsletterRouteImport } from './routes/admin.newsletter'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesReplacementRoute = PoliciesReplacementRouteImport.update({
  id: '/policies/replacement',
  path: '/policies/replacement',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRefundRoute = PoliciesRefundRouteImport.update({
  id: '/policies/refund',
  path: '/policies/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderNumberRoute = OrdersOrderNumberRouteImport.update({
  id: '/$orderNumber',
  path: '/$orderNumber',
  getParentRoute: () => OrdersRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OrdersRouteChildren {
  OrdersOrderNumberRoute: typeof OrdersOrderNumberRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderNumberRoute: OrdersOrderNumberRoute,
}

const OrdersRouteWithChildren = OrdersRoute._addFileChildren(OrdersRouteChildren)

interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  StoreRoute: typeof StoreRoute
  TrackRoute: typeof TrackRoute
  WishlistRoute: typeof WishlistRoute
  PoliciesRefundRoute: typeof PoliciesRefundRoute
  PoliciesReplacementRoute: typeof PoliciesReplacementRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRouteWithChildren,
  StoreRoute: StoreRoute,
  TrackRoute: TrackRoute,
  WishlistRoute: WishlistRoute,
  PoliciesRefundRoute: PoliciesRefundRoute,
  PoliciesReplacementRoute: PoliciesReplacementRoute,
  ProductsSlugRoute: ProductsSlugRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: FullPaths
  fileRoutesByTo: FileRoutesByTo
  to: To
  id: Id
  fileRoutesById: FileRoutesById
}

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/store': typeof StoreRoute
  '/track': typeof TrackRoute
  '/wishlist': typeof WishlistRoute
  '/policies/refund': typeof PoliciesRefundRoute
  '/policies/replacement': typeof PoliciesReplacementRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/$orderNumber': typeof OrdersOrderNumberRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/store': typeof StoreRoute
  '/track': typeof TrackRoute
  '/wishlist': typeof WishlistRoute
  '/policies/refund': typeof PoliciesRefundRoute
  '/policies/replacement': typeof PoliciesReplacementRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/$orderNumber': typeof OrdersOrderNumberRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
}

export type FullPaths =
  | '/'
  | '/admin'
  | '/admin-login'
  | '/cart'
  | '/checkout'
  | '/contact'
  | '/login'
  | '/orders'
  | '/store'
  | '/track'
  | '/wishlist'
  | '/policies/refund'
  | '/policies/replacement'
  | '/products/$slug'
  | '/admin/'
  | '/orders/$orderNumber'
  | '/admin/messages'
  | '/admin/newsletter'
  | '/admin/orders'
  | '/admin/products'
  | '/admin/settings'

export type To =
  | '/'
  | '/admin'
  | '/admin-login'
  | '/cart'
  | '/checkout'
  | '/contact'
  | '/login'
  | '/orders'
  | '/store'
  | '/track'
  | '/wishlist'
  | '/policies/refund'
  | '/policies/replacement'
  | '/products/$slug'
  | '/admin/'
  | '/orders/$orderNumber'
  | '/admin/messages'
  | '/admin/newsletter'
  | '/admin/orders'
  | '/admin/products'
  | '/admin/settings'

export type Id =
  | '__root__'
  | '/'
  | '/admin'
  | '/admin-login'
  | '/cart'
  | '/checkout'
  | '/contact'
  | '/login'
  | '/orders'
  | '/store'
  | '/track'
  | '/wishlist'
  | '/policies/refund'
  | '/policies/replacement'
  | '/products/$slug'
  | '/admin/'
  | '/orders/$orderNumber'
  | '/admin/messages'
  | '/admin/newsletter'
  | '/admin/orders'
  | '/admin/products'
  | '/admin/settings'

export interface FileRoutesById {
  '__root__': typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/store': typeof StoreRoute
  '/track': typeof TrackRoute
  '/wishlist': typeof WishlistRoute
  '/policies/refund': typeof PoliciesRefundRoute
  '/policies/replacement': typeof PoliciesReplacementRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/$orderNumber': typeof OrdersOrderNumberRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
}
